### ISSUE TITLE
Bytes should never be null on PBJ generated classes

### ISSUE THREAD

**Issue by rbair23** [hashgraph/pbj#106]
### Problem

Given a generated class that supports protobuf bytes, we represent this as a `Bytes` object. A lot of code is doing null checks when a default Bytes.EMPTY return from the pbj generated object would have made the code simpler.

### Solution

According to the [specification](https://protobuf.dev/programming-guides/proto3/), the default value for `bytes` is empty bytes. And in our parser we honor this, making sure the bytes are always Bytes.EMPTY or equivalent, and never null. But we do not mark the Bytes argument in the record as NonNull, so code that uses a PBJ object tries to be defensive when it shouldn't need to. If we annotated this properly, then static analysis could prove it is safe. And we should absolutely forbid null in the builder for Bytes arguments.

**Comment by jsync-swirlds** [comment]
Rather than forbid null in the builder; perhaps just translate null to Bytes.EMPTY but still annotate with `@NonNull`, so we support static analysis, but don't actually crash.
