### ISSUE TITLE
Wrap unchecked Exceptions in checked Exception

### ISSUE THREAD

**Issue by netopyr** [hashgraph/pbj#114]
### Problem

Currently generated implementations of `Codec.parse()` and `Codec.parseStrict()` can throw (undocumented) unchecked Exceptions. We have already discovered several cases where these Exceptions were not caught, causing havoc because, as unchecked Exceptions, they can pop up anywhere.

The developer can not really be blamed as these were not documented. In addition, it is pretty hard to find these failures in tests, because they only appear if a broken input is passed to `parse()` that throws the unchecked Exception.

### Solution

To enforce dealing with these error conditions, we agreed to introduce a new checked Exception called `ParseException`. All unchecked Exceptions that can be thrown during `parse` or `parseStrict` must be caught and wrapped in a `ParseException`. This would force a developer to deal with a failed parsing correctly.

### Alternatives

- Do nothing - too risky.
- Replace unchecked Exceptions with checked Exceptions directly in PBJ - too much work and questionable if we are able to find all cases.

**Comment by anthony-swirldslabs** [comment]
The parsing methods already declare the IOException as a checked exception that they throw. To avoid having to add another checked exception to the method signatures (and hence avoid modifying all the places where the parsing methods are called), I'll be wrapping any unchecked exceptions in IOException which existing code should already catch.

**Comment by netopyr** [comment]
I don't think we should mix parsing and I/O but I do not have a strong opinion.

The suggested solution was discussed with @rbair23. Please check if he is ok with this change (if you have not already done so.)

**Comment by anthony-swirldslabs** [comment]
@netopyr : Thanks for the comment. I discussed this with @rbair23 and the Platform Data team, and Richard actually suggested to replace the IOException with a checked ParseException in Codec.parse() methods, and throw the latter when parsing fails for any reason. The `cause` throwable of the ParseException will provide details on the nature of the failure - it may be an IOException, or any other exception that the parsing implementation may throw.

That's what I'm doing in the latest version of the fix at: https://github.com/hashgraph/pbj/pull/172

**Comment by anthony-swirldslabs** [comment]
One pending task: upgrade PBJ to 0.7.14 with this fix, and make changes in a few repos in hedera-services to handle the ParseException with this upgraded dependency.

**Comment by anthony-swirldslabs** [comment]
A new version of PBJ 0.7.14 is about to make it to Maven at https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions

Once there, I'll prepare a fix in hedera-services to take the dependency and to update existing usages of Codec.parse() to catch the ParseException instead of the IOException.

**Comment by anthony-swirldslabs** [comment]
> > A new version of PBJ 0.7.14 is about to make it to Maven at https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
> > Once there, I'll prepare a fix in hedera-services to take the dependency and to update existing usages of Codec.parse() to catch the ParseException instead of the IOException.
> 
> I think changing the API like this is considered a breaking change, and would require updating the version to 0.8.0 to reflect that. I seem to recall Nathan arguing for exactly that in a thread on slack.
> 
> Thoughts?

Here's what @rbair23 actually said on Slack:

> But, suppose we let it be a ParseException. Under semantic versioning, breaking changes require a bump in the major version... except when the major version is 0. A major version of 0 means nothing is guaranteed from build to build, so you should be fine.

And I tend to agree because it's not like PBJ is widely used. I've made all the required changes in the `develop` branch of hedera-services, and I believe that Nick is covering stuff in his own private branch on his own. Please note that whether the version of the library is changed to 0.7.x or 0.8 - it wouldn't eliminate the need for the changes. And since the changes are already done/being in progress in private branches, I don't really see a problem here.

**Comment by jsync-swirlds** [comment]
> > > A new version of PBJ 0.7.14 is about to make it to Maven at https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
> > > Once there, I'll prepare a fix in hedera-services to take the dependency and to update existing usages of Codec.parse() to catch the ParseException instead of the IOException.
> > 
> > 
> > I think changing the API like this is considered a breaking change, and would require updating the version to 0.8.0 to reflect that. I seem to recall Nathan arguing for exactly that in a thread on slack.
> > Thoughts?
> 
> Here's what @rbair23 actually said on Slack:
> 
> > But, suppose we let it be a ParseException. Under semantic versioning, breaking changes require a bump in the major version... except when the major version is 0. A major version of 0 means nothing is guaranteed from build to build, so you should be fine.
> 
> And I tend to agree because it's not like PBJ is widely used. I've made all the required changes in the `develop` branch of hedera-services, and I believe that Nick is covering stuff in his own private branch on his own. Please note that whether the version of the library is changed to 0.7.x or 0.8 - it wouldn't eliminate the need for the changes. And since the changes are already done/being in progress in private branches, I don't really see a problem here.

Fair point.  Just noting the possible concern.  Also, it kind of defeats the purpose of using semantic versioning if it doesn't really tell us anything about the product or API stability.  At that point we might as well just use a single number...  Not worth making a significant change here, but something to consider in the future.

**Comment by anthony-swirldslabs** [comment]
> Fair point. Just noting the possible concern. Also, it kind of defeats the purpose of using semantic versioning if it doesn't really tell us anything about the product or API stability. At that point we might as well just use a single number... Not worth making a significant change here, but something to consider in the future.

Generally, I agree. And this will become very important once we release PBJ 1.0. While we're still building 0.x though, I'll keep this point in mind and will try to choose 0.8 etc. if there's a breaking change in the API in the future. But for this particular change, I'll leave the things as they are for the reasons that I outlined above.

**Comment by anthony-swirldslabs** [comment]
The PR at https://github.com/hashgraph/hedera-services/pull/11151 has been merged to the `develop` branch. The hedera-services repo now depends on PBJ 0.7.14 and handles the ParseException when calling Codec.parse() and related methods. This completes this story.
