### ISSUE TITLE
Revisit data access exceptions in RandomAccessData, Bytes, BufferedData, and other classes

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/pbj#118]
Here is one of the methods in `RandomAccessData` interface:

```
    /**
     * Gets the signed byte at the given {@code offset}.
     *
     * @param offset The offset into data to get a byte from.
     * @return The signed byte at given {@code offset}
     * @throws BufferUnderflowException if the buffer is empty
     * @throws IndexOutOfBoundsException If the given {@code offset} is negative or not less than {@link #length()}
     */
    byte getByte(final long offset);
```

Method semantics is "get a byte at the given offset", which is identical to byte arrays. IOOBE is consistent with what exceptions are used by arrays, but BufferUnderflowException looks alien here. These BufferXYZExceptions are used by buffers on sequential access, when there is no more data to read / write. On random access, java.nio buffer classes throw IOOBE, too.

This ticket is to iterate over PBJ classes and interfaces and make sure exceptions used to indicate illegal access are consistent across code.

**Comment by poulok** [comment]
Please speak with @rbair23 before changing the strategy for exceptions.
