### ISSUE TITLE
Identify unit testing gaps and fill them

### ISSUE THREAD

**Issue by poulok** [hashgraph/pbj#125]
Identify any gaps in unit test coverage and areas that need some more and fill them. Out of the three areas (code generator tool, runtime library, and generated code), the runtime library does need more coverage. The code generator tool probably needs some cleanup and maybe more tests for what remains.

```[tasklist]
### Tasks
- [x] Check that the new `hashcode()` and `equals()` methods are tested in the generated code, including corner cases
- [ ] #28
- [ ] To do - add more specific tasks
```

**Comment by anthony-swirldslabs** [comment]
Not sure about any corner cases, but the generated Test files for models include dedicated tests for the generated equals() and hashCode() methods. So I'm resolving that task.

**Comment by anthony-swirldslabs** [comment]
In the recent PR #166 , the coverage has been improved for the code that seemed worth covering. The remaining gaps don't seem critical and can be tackled as we modify the code in the future.
