### ISSUE TITLE
PBJ does not support protobuf "map"

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#14]
### Description

Need to add support for https://developers.google.com/protocol-buffers/docs/proto3#maps. They are currently not used in HAPI so support was not needed yet.

### Steps to reproduce

try to compile a proto file with map in it.

### Hedera network

other

### Version

0.1.0

### Operating system

None

**Comment by anthony-swirldslabs** [comment]
Maps are delivered to PBJ v0.9.0 under https://github.com/hashgraph/pbj/issues/254 .
