### ISSUE TITLE
Default Enum values are expensive

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/pbj#157]
### Problem

`ResponseHeader.Builder` has this code:
```
        private ResponseCodeEnum nodeTransactionPrecheckCode = ResponseCodeEnum.values()[0];
        private ResponseType responseType = ResponseType.values()[0];
```
Every time the builder is instantiated an array of all values is allocated and populated for each Enum only to get the first (default) value and discard the rest.

### Solution

Can generated code for Enums provide a static `defaultValue()` method?

**Comment by anthony-swirldslabs** [comment]
The method already exists. It's called `fromProtobufOrdinal`. Simply replace usages such as this:

```java
ResponseCodeEnum.values()[0]
```

with

```java
ResponseCodeEnum.fromProtobufOrdinal(0)
```

and that should resolve the issue.

**Comment by anthony-swirldslabs** [comment]
Actually, the Builder in PBJ still uses the old approach.
