### ISSUE TITLE
Failure to process Int64Value in a model

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/pbj#170]
### Description

https://github.com/hashgraph/hedera-protobufs/pull/312 added an `Int64Value` field to services/contract_call_local.proto recently.

Ever since, PBJ integration tests fail to build: https://github.com/hashgraph/pbj/actions/runs/7545723496/job/20541986405

with a message:

```
> Task :generatePbjSource FAILED
Exception while processing file: /runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/contract_call_local.proto

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generatePbjSource'.
> Failed to find fully qualified message type for [Int64Value] in file [/runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/contract_call_local.proto] imports = [/runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/contract_types.proto, /runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/basic_types.proto, /runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/response_header.proto, /runner/_work/pbj/pbj/pbj-integration-tests/build/repos/hapi/services/query_header.proto]
```

### Steps to reproduce

See the failing build above. Build in pbj-integration-tests should fail this way.

### Hedera network

other

### Version

v

### Operating system

None

**Comment by anthony-swirldslabs** [comment]
The type reference `Int64Value` should be prefixed with `google.protobuf.`, similar to:

https://github.com/hashgraph/hedera-protobufs/blob/8342c9193e5efb7e035972e7ce4ce6bd2d4b4211/services/contract_call_local.proto#L133

I have a fix for this. Now I just need to get permissions to push to that repo to publish a PR.

**Comment by imalygin** [comment]
Here is the fix pending: 

https://github.com/hashgraph/hedera-protobufs/pull/316

**Comment by anthony-swirldslabs** [comment]
This issue can now be resolved because 1) it's being fixed under a different issue (see link above); and 2) it's not really a bug in PBJ.
