### ISSUE TITLE
PBJ generated code compilation fails when just using `google.protobuf.BytesValue`

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/pbj#174]
### Description

When any protobuf file just contains `google.protobuf.BytesValue`, the generated `*TransactionBodyProtoCodec` doesn't import `Bytes` correctly for the `google.protobuf.BytesValue`.

### Steps to reproduce

Use val hapiProtoBranchOrTag = "add-pbj-types-for-state" in hedera-node/hapi/build.gradle.kts in services
Compile using ./gradlew assemple. The compilation fails with the following message
```
  symbol:   class Bytes
  location: class TokenUpdateTransactionBodyProtoCodec
/Users/neeharikasompalli/Documents/Hedera/Repos/repo2/hedera-services/hedera-node/hapi/build/generated/source/pbj-proto/main/java/com/hedera/hapi/node/token/codec/TokenUpdateTransactionBodyProtoCodec.java:595: error: cannot find symbol
                        final Bytes value;

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

**Comment by imalygin** [comment]
This is fixed in PBJ 0.7.12. I'll update `hedera-services` as soon as possible
