### ISSUE TITLE
CompareTo Generation fails if fields include underscores

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/pbj#175]
### Description

If a field in a proto message contains underscores in the name, the new CompareTo generation fails with two messages:
 * `Exception while processing file: /Users/user/Projects/Hashgraph/Pbj/pbj-integration-tests/src/main/proto/comparable.proto`
 * `Cannot invoke "com.hedera.pbj.compiler.impl.Field.optionalValueType()" because "f" is null`.  

Note that no further information is given, so it is a particularly difficult error to track down.

### Steps to reproduce

1. Modify pbj-integration-tests/src/main/proto/comparable.proto
   * change `bytes bytes` to `bytes bytes_field` on line 26
   * change `, bytes"`, to `, bytes_field"` on line 18
1. run `./gradlew clean assemble -Dsonar.gradle.skipCompile=true --warning-mode=summary --no-daemon --no-build-cache --no-configuration-cache`

The compilation will fail with the referenced error

**Comment by jsync-swirlds** [comment]
Here is a patch that resolves this issue (and includes an abbreviated stack trace in compiler output for compiler exceptions).
[fix-175-CompareTo-Generation-fails-if-fields-include.patch](https://github.com/hashgraph/pbj/files/13992362/fix-175-CompareTo-Generation-fails-if-fields-include.patch)

**Comment by poulok** [comment]
@jsync-swirlds is your branch ready for review? Do you need someone to take it over?

**Comment by jsync-swirlds** [comment]
I sent a draft PR.  I have bandwidth to complete the PR if that's easiest.
