### ISSUE TITLE
Generated hashCode() for OneOf classes must not depend on Enum.hashCode()

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/pbj#227]
All PBJ objects have auto-generated `hashCode()` implementation. For `OneOf` fields, hash codes are calculated like this:

```java
        return (31 + kind.hashCode()) * 31 + (value == null ? 0 : value.hashCode());
```

`kind` above is a enum, so its hash code is actually `Enum.hashCode()`. Here is the problem: this method is not deterministic, it returns different values across process runs:

```java
        int hc = hash;
        if (hc == 0) {
            hc = hash = System.identityHashCode(this);
        }
        return hc;
```

Since we use hash codes in long-term storage, they must be the same across node runs. It means `Enum.hashCode()` must not be used anywhere in our code. There may be other usages than in `OneOf`.

One quick option is to use `kind.ordinal()` (or some derivative) instead of `kind.hashCode()`, but there may be better solutions.

**Comment by netopyr** [comment]
Using `kind.ordinal()` seems risky. If somebody adds an entry or reorders the elements, the code will break in unexpected ways. Is there a way to define this number explicitly in protobuf?

**Comment by anthony-swirldslabs** [comment]
> Using `kind.ordinal()` seems risky. If somebody adds an entry or reorders the elements, the code will break in unexpected ways. Is there a way to define this number explicitly in protobuf?

`Enum.name().hashCode()` should be good, I think, and not require any explicit definitions. Please see the linked PR.

**Comment by jsync-swirlds** [comment]
> Using `kind.ordinal()` seems risky. If somebody adds an entry or reorders the elements, the code will break in unexpected ways. Is there a way to define this number explicitly in protobuf?

Might be worth noting that adding, removing, or reordering an enum in protobuf breaks compatibility, and should not, ever, be done if you want to use the definition between versions.
