### ISSUE TITLE
`ReadableSequentialDataInputStream.read()` returns signed int

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/pbj#246]
The javadoc for `InputStream.read()` reads:
```
Reads the next byte of data from the input stream. The value byte is returned as an {@code int} 
in the range {@code 0} to {@code 255}. If no byte is available because the end of the stream 
has been reached, the value {@code -1} is returned.
```

The method `ReadableSequentialDataInputStream.read()` converts a byte directly to an int in its signed form. This violates the interface contract and the data is interpreted wrongly and throws an EOFException when a `-1` is encountered. 

`Bytes.toInputStream()` does this correctly.

**Comment by anthony-swirldslabs** [comment]
I'm upgrading the PBJ version in `hedera-services` to v0.8.7 at https://github.com/hashgraph/hedera-services/pull/12939
