### ISSUE TITLE
`Bytes.getInt()` ignores start

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/pbj#256]
Some methods in the `Bytes` class seem to ignore the `start` variable and assume that it is `0`. While the single parameter versions seems to be ok:
```
    public int getInt(long offset) {
        return UnsafeUtils.getInt(this.buffer, Math.toIntExact((long)this.start + offset));
    }
```
The version with a `byteOrder` just ignores `start`:
```
    public int getInt(long offset, @NonNull ByteOrder byteOrder) {
        return byteOrder == ByteOrder.BIG_ENDIAN ? this.getInt(offset) : Integer.reverseBytes(this.getInt(offset));
    }
```

A similar issue exists with `getLong`.

**Comment by anthony-swirldslabs** [comment]
There's no any bugs here. As you can notice from the code snippets that you quoted above, the `getInt(long offset, @NonNull ByteOrder byteOrder)` delegates to `this.getInt(offset)`.

And per the very first code snippet in the issue description, the `getInt(long)` implementation does respect the `start`. So the `getInt(long, ByteOrder)` implementation doesn't need to do anything special as long as it delegates to the original method.

I know this may look a bit confusing and I spent quite some time when I was fixing the original issue to go through the code and ensure that the `start` is respected everywhere. And I believe it is.

Please feel free to reopen the issue if you find a place that indeed disregards the `start`.
