### ISSUE TITLE
Write tests for ReadableSequentialData

### ISSUE THREAD

**Issue by rbair23** [hashgraph/pbj#28]
Similar to WritableSequentialData, we need tests for ReadableSequentialData that use a stub for readByte, so we can verify everything there passes.

**Comment by artemananiev** [comment]
Closing this ticket as it's already implemented. ReadableSequentialTestBase now extends ReadableTestBase by adding a few sequential test cases. Then it's extended by ReadableStreamingDataTest (using ReadableStreamingData) and ReadableSequentialDataTest (using stubbed implementation).
