### ISSUE TITLE
PBJ parsing from GZIP streams is horrible slow

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#297]
### Description

Parsing a large protobuf file with > 50K objects from a FileInputStream using PBJ took 6.279 seconds! Using protoc it took 578ms. So we are much much slower!
`Block block = Block.PROTOBUF.parse(new ReadableStreamingData(GZIPInputStream(new FileInputStream(blockProtoFile)));`
If you read file into memory first than PBJ(302ms) is faster than protoc(491ms).
`Block block = Block.PROTOBUF.parse(Bytes.wrap(new GZIPInputStream(new FileInputStream(blockProtoFile)).readAllBytes()));`

### Steps to reproduce

Parse a large protobuf file with 10s of thousands of objects from a stream. Attached here is example file used for testing and numbers above. It is a [Hedera HAPI Block object](https://github.com/hashgraph/hedera-protobufs/blob/main/block/stream/block.proto) at root level in file.
[000000000000000000000000000000001558.blk.gz](https://github.com/user-attachments/files/17246578/000000000000000000000000000000001558.blk.gz)

### Version

0.9.2

### Operating system

macOS

**Comment by artemananiev** [comment]
Code snippet:

```java
		final Path path = Path.of("...");

		long start, end;

		start = System.currentTimeMillis();
		try (final InputStream fin = Files.newInputStream(path);
				final GZIPInputStream in = new GZIPInputStream(fin)) {
			com.hedera.hapi.block.stream.protoc.Block protocBlock = com.hedera.hapi.block.stream.protoc.Block.parseFrom(in);
			end = System.currentTimeMillis();
		}
		System.err.println("Protoc time: " + (end - start));

		start = System.currentTimeMillis();
		try (final InputStream fin = Files.newInputStream(path);
				final GZIPInputStream gzin = new GZIPInputStream(fin)) {
			final Block pbjBlock = Block.PROTOBUF.parse(new ReadableStreamingData(gzin));
			end = System.currentTimeMillis();
		}
		System.err.println("PBJ time: " + (end - start));
```

**Comment by artemananiev** [comment]
Some early observations:

* Wrapping the file stream or the GZIP stream into `BufferedInputStream` doesn't help
* Reading the file into a byte array and then parsing from there doesn't help

**Comment by artemananiev** [comment]
A minor correction to the comment above. This code is as slow as the original version:

```java
		start = System.currentTimeMillis();
		try (final InputStream fin = Files.newInputStream(path);
				final BufferedInputStream bufin = new BufferedInputStream(fin);
				final GZIPInputStream gzin = new GZIPInputStream(bufin)) {
			final Block pbjBlock = Block.PROTOBUF.parse(new ReadableStreamingData(gzin));
			end = System.currentTimeMillis();
		}
		System.err.println("PBJ time: " + (end - start));
```

However, if a buffer is used between GZIP input stream and the codec, it makes PBJ run as fast (or even slightly faster) than protoc:

```java
		start = System.currentTimeMillis();
		try (final InputStream fin = Files.newInputStream(path);
				final GZIPInputStream gzin = new GZIPInputStream(fin);
				final BufferedInputStream bufin = new BufferedInputStream(gzin)) {
			final Block pbjBlock = Block.PROTOBUF.parse(new ReadableStreamingData(bufin));
			end = System.currentTimeMillis();
		}
		System.err.println("PBJ time: " + (end - start));
```

**Comment by artemananiev** [comment]
With the right buffering, PBJ is not slower than protoc.
