### ISSUE TITLE
Great convenience API for converting from Bytes to byte array

### ISSUE THREAD

**Issue by rbair23** [hashgraph/pbj#33]
### Problem

While we do have a number of `getBytes` methods on `Bytes` to populate an array, we're missing a simple `asByteArray` method that will create a new byte array of the correct size and populate it with a copy of the data all in one call. Right now, I have to do a lot of conversions between Bytes and byte arrays because the hashgraph platform doesn't support Bytes yet. As such, I have to write a lot of boilerplate code like:

```
final var compressedByteArray = new byte[(int) keyBytes.length()];
keyBytes.getBytes(0, compressedByteArray);
```

### Solution

I'd like an API such as:

```
final var compressedByteArray = keyBytes.asByteArray();
```

**Comment by LLITCHEV** [comment]
@rbair23 A quick question... Does the returned bytes need to be different than the bytes in the internal buffer? Should the returned value be a copy (slow) or it is okay to return the bytes that already exist? Shall the user be allowed to modify the data in the buffer?

**Comment by LLITCHEV** [comment]
@rbair23 After talking to @jasperpotts, it is as I expected... I need to clone the bytes since the Bytes object is better to stay immutable.

**Comment by LLITCHEV** [comment]
Implemented with https://github.com/hashgraph/pbj/pull/46.
