### ISSUE TITLE
Update the `hashCode` function to avoid collisions

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/pbj#35]
Change generated record files for messages with a single number field to not use default generated dashcode() function but use the one below. 
This is done for performance reasons so that we have better balanced hashing buckets.

```
public static long perm64(long x) {
        // Shifts: {30, 27, 16, 20, 5, 18, 10, 24, 30}
        x += x << 30;
        x ^= x >>> 27;
        x += x << 16;
        x ^= x >>> 20;
        x += x << 5;
        x ^= x >>> 18;
        x += x << 10;
        x ^= x >>> 24;
        x += x << 30;
        return x;
    }

```

**Comment by LLITCHEV** [comment]
PR https://github.com/hashgraph/pbj/pull/38
