### ISSUE TITLE
Let Bytes be Comparable

### ISSUE THREAD

**Issue by rbair23** [hashgraph/pbj#36]
### Problem

I have the need to sort Bytes objects. I don't want to have to convert them to byte arrays.

### Solution

 It would be nice if they were either `Comparable`, or there were some built in `Comparators` that could sort. One sorting strategy would be shortest to longest, and lowest bytes to highest bytes. Such that:

```
{ 7 }
{ 1, 2 }
{ 1, 2, 3 }
{ 2, 1, 1 }
{ 5, 6, 7, 8 }
{ 0, 1, 0, 1, 0 }
```

In the above example, we can see that shorter rows are sorted higher than longer rows, and lower bytes are sorted before higher bytes when given the same length.

**Comment by rbair23** [comment]
If we do this, there is some code in `TransactionChecker` in services on the consensus node that could be improved.

**Comment by jasperpotts** [comment]
@rbair23 This feels odd, you would have expected default sort order on value not just length?

**Comment by rbair23** [comment]
I'm sure there are several interesting ways to sort (in my case, I want length and then by order). Rather than Bytes being comparable itself, we could just have Bytes have some built in comparators. You could have SORT_BY_LENGTH and SORT_BY_VALUE and then combine them Comparator.thenComparing, like `SORT_BY_LENGTH.thenComparing(SORT_BY_VALUE)`. That way we don't have to pick just one way.

**Comment by LLITCHEV** [comment]
Fixed with https://github.com/hashgraph/pbj/pull/41
