### ISSUE TITLE
Add support to throw on unknown protobuf fields

### ISSUE THREAD

**Issue by rbair23** [hashgraph/pbj#4]
The Parser should have a flag, such that when using the parser it will throw an exception if it encounters an unknown field. While this breaks the "forward compatible" nature of protobuf, we need this behavior for the consensus nodes, so that random transactions sent by users are rejected if they have unsupported fields. Or, we parse past them, keep a count of unknown fields, and make it easy to inspect this.

**Comment by artemananiev** [comment]
This is what `Codec.parseStrict()` does. The only difference between `parse()` and `parseStrict()` is that strict parsing throws IOExceptions for unknown fields, while regular parsing just skips them. This is what this ticket is about, so I'm closing it as already implemented.
