### ISSUE TITLE
Add Convenience Methods

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#42]
There are a bunch of places that extra methods would make usage more efficient or cleaner.

---
### Nice 1

We have `Bytes.writeTo(ByteBuffer)` which is nice but I have no way to pass to a `MessageDigest` without a copy. So can we please add:
`Bytes.writeTo(MessageDigest)` which calls `MessageDigest.update()` with the internal `byte[]` of Bytes.

---
### Nice 2

We have `Bytes.writeTo(ByteBuffer)` which is nice but I have no way to pass to a `OutputStream` without a copy. So can we please add:
`Bytes.writeTo(OutputStream)` which calls `OutputStream.write()` with the internal `byte[]` of Bytes.

---
### Nice 3

It would be really helpful in `Codec` and hence` <GeneratedRecord>.PROTOBUF` class to add a method `toBytes()` that writes the object out in protobuf format and returns it as a Bytes object.

it could be implemented like this to start with, adding a more optimal implementation later

```
public Bytes toBytes(@NonNull T item) {
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        WritableStreamingData writableStreamingData = new WritableStreamingData(byteArrayOutputStream);
        try {
            write(item, writableStreamingData);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return Bytes.wrap(byteArrayOutputStream.toByteArray());
}
````

**Comment by LLITCHEV** [comment]
Addressed with https://github.com/hashgraph/pbj/pull/43
