### ISSUE TITLE
Improve Bytes Performance

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#59]
### Problem

Bytes is slow using the default read methods from the RandomAccessData interface.

### Solution

Implement all RandomAccessData methods directly in Bytes with direct access to array data. Either with normal array access or Misc.Unsafe if it is safe enough and much faster. Creating fast path implementations for all RandomAccessData methods.

**Comment by LLITCHEV** [comment]
https://github.com/hashgraph/pbj/pull/69
