### ISSUE TITLE
Add Tests for Malformed Data

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#68]
### Problem

PBJ has not been fully tested for parsing streams of badly formed data. 

### Solution

Write unit tests and file issues as needed to fix any cases where input data could cause problems. As long as all badly formed data can not cause high resource usage like CPU or Memory and it throws a ParseException if anything goes wrong then we are all good.

Examples of badly formed data could be:

- Very deep nested messages
- Large Lists
- Large lengths for size of length encoded data
- Probably Others

Also adding fuzz testing could be a good idea to make really sure.

**Comment by poulok** [comment]
Start with 6k max buffer size for fuzz testing. Then test with larger sizes.

**Comment by anthony-swirldslabs** [comment]
The first in a series of PRs to build a fuzz testing framework: https://github.com/hashgraph/pbj/pull/138

**Comment by anthony-swirldslabs** [comment]
A second PR that introduces the FuzzTest class: https://github.com/hashgraph/pbj/pull/140

**Comment by anthony-swirldslabs** [comment]
As a part of this story we found a few parsing issues in PBJ and fixed them. The ultimate outcome is a new fuzz testing framework that generates malformed data and checks whether PBJ can parse it or throw an exception, and at the same time compares the result with what Google Protobuf does. The fuzz tests run when the regular `test` target runs in the pbj-integration-tests package. They can also be run manually as:

```
$ gr fuzzTest --info
...
    Fuzz tests are configured to use a FIXED seed for `new Random(seed)`, and the seed value for this run is: 837582698436792
    Fuzz tests PASSED with passRate = 100.00% and deserializationFailedMean = 98.30%
    Total number of SingleFuzzTest runs: 1257180
    Elapsed time: 34 seconds
...
```

This completes this particular story. We're working on further enhancements for PBJ at https://github.com/hashgraph/pbj/issues/164 .
