### ISSUE TITLE
Some sizeOf methods aren't exposed publicly from ProtoWriterTools

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/pbj#74]
Several `sizeOfXYZ()` methods are not public in `ProtoWriterTools`. For example:

* sizeOfTag()
* sizeOfVarInt32()
* sizeOfUnsignedVarInt32()
* etc.

I don't know why other methods are public, but these aren't. My guess is these methods are too low level and aren't expected to be used by 3rd-party code. For example, to get size of an integer, they should always use `sizeOfInteger()`, which internally calls these private methods.

However, in MerkleDb PBJ code I do need at least `sizeOfTag()`, since MerkleDb writes and reads field tags manually, not using codecs. Also, `sizeOfInteger()` has valid optimization of skipping default int values (i.e. zero), but in case of MerkleDb it's sometimes helpful to write default values, too, to make file structure a little bit more regular (still protobuf compatible).

**Comment by artemananiev** [comment]
It looks like there are some utility methods in `CodecOutputStream`, but this is a class from com.google.protobuf, which isn't directly used by MerkleDb.

**Comment by LLITCHEV** [comment]
Make the methods above public...

**Comment by artemananiev** [comment]
Methods currently copied from PBJ repo to MerkleDb PBJ branch:

* sizeOfTag(field, wireType) - copied from ProtoWriterTools
* sizeOfVarInt32(value) - from ProtoWriterTools
* sizeOfUnsignedVarInt32(value) - from ProtoWriterTools
* sizeOfVarInt64(value)
* sizeOfUnsignedVarInt64(value)
* sizeOfDelimited(field, length) - copied from ProtoWriterTools

One more method is not related to sizes, but also copied:

* writeTag(writeableSeqOut, field)

It would also be great to have a public method to read the next tag / field number from a buffer/stream. Today I do it by hand in several places:

```java
            final int tag = in.readVarInt(false);
            final int number = tag >> TAG_FIELD_OFFSET;
```
