### ISSUE TITLE
`parseStrict()` not throwing given partial message

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/pbj#96]
### Description

The attached file is a partial serialization of a [`ServicesConfigurationList`](https://github.com/hashgraph/hedera-protobufs/blob/f36e05bd6bf3f572707ca9bb338f5ad6421a4241/services/basic_types.proto#L1458) message. When parsed using a `protoc`-generated parser, an exception is thrown. No exception is thrown when parsed using a PBJ-generated parser. I.e., this test does not pass:

```
    @Test
    void parseStrictNotThrowingOnIncompleteMessage() throws IOException {
        final var hexed = Files.readString(Paths.get("<path-to-file>")).trim();
        final var unhexed = CommonUtils.unhex(hexed);
        assertThrows(InvalidProtocolBufferException.class, () ->
                com.hederahashgraph.api.proto.java.ServicesConfigurationList.parseFrom(unhexed));
        assertThrows(Exception.class, () ->
                com.hedera.hapi.node.base.ServicesConfigurationList.PROTOBUF.parseStrict(
                        BufferedData.wrap(unhexed)));
    }
```

[hexedPartialServicesConfigurationList.txt](https://github.com/hashgraph/pbj/files/12541525/hexedPartialServicesConfigurationList.txt)

### Steps to reproduce

As above.

### Hedera network

other

### Version

`develop`

### Operating system

None

**Comment by rbair23** [comment]
The underlying issue is that in `ProtoParserTools` the `getString` method doesn't validate that it read all the required bytes.

```
public class ProtoParserToolsTest {
    @Test
    void readStringWithInsufficientData() {
        // Given a buffer where the first varInt is the length, and is longer than the number of bytes in the buffer.
        final var seq = BufferedData.allocate(3);
        seq.writeVarInt(10, false);
        seq.position(0);

        // When we parse that sequence, then we fail because there are not enough bytes to continue parsing.
        assertThatThrownBy(() -> ProtoParserTools.readString(seq))
                .isInstanceOf(RuntimeException.class)
                .hasMessage("Insufficient data to read string");
    }
}
```

Above is a test case that can be added. We should likewise verify the other methods like parsing varint and longs and floats and bytes, etc, to make sure all work with fewer bytes than they should have. Jasper recommended a test where we have one of every type of thing, encode it, truncate by one byte, parse each, and verify they all throw. This is a good idea.

**Comment by rbair23** [comment]
I think we should focus on writing the test first, and fixing the parse methods second. We may not need to worry about updating the code generation at all (and it would be faster to do the check once instead of twice).

**Comment by LLITCHEV** [comment]
Yes... the fixes are in the test generation. I am adding tests right now.
